version: '3.8'

services:
  yaw-backend:
    environment:
      - DB_HOST=mysql_db
      - ALLOWED_HOSTS=api.illustration.local,illustration.local,localhost,127.0.0.1,192.168.0.105
    networks:
      - app-network

  yaw-frontend:
    build:
      args:
        - VITE_API_URL=http://api.illustration.local/api
    environment:
      - VITE_API_URL=http://api.illustration.local/api
